service: halcyon-dotnet-api

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: dev
  region: eu-west-1
  memorySize: 1024
  logRetentionInDays: 3
  environment:
    DEFAULT_CONNECTION: ${env:DEFAULT_CONNECTION, ''}
    JWT_SECURITYKEY: ${env:JWT_SECURITYKEY, ''}
    SEED_EMAILADDRESS: ${env:SEED_EMAILADDRESS, ''}
    SEED_PASSWORD: ${env:SEED_PASSWORD, ''}
    EMAIL_HOST: ${env:EMAIL_HOST, ''}
    EMAIL_PORT: ${env:EMAIL_PORT, ''}
    EMAIL_USERNAME: ${env:EMAIL_USERNAME, ''}
    EMAIL_PASSWORD: ${env:EMAIL_PASSWORD, ''}
    EMAIL_NOREPLY: ${env:EMAIL_NOREPLY, ''}
    FACEBOOK_APPID: ${env:FACEBOOK_APPID, ''}
    FACEBOOK_APPSECRET: ${env:FACEBOOK_APPSECRET, ''}
    GOOGLE_CLIENTID: ${env:GOOGLE_CLIENTID, ''}

package:
  artifact: Halcyon.Api/bin/release/netcoreapp2.1/deploy-package.zip

functions:
  app:
    handler: Halcyon.Api::Halcyon.Api.LambdaEntryPoint::FunctionHandlerAsync
    events:
      - http:
          path: /{proxy+}
          method: ANY
