service: halcyon-dotnet-api

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: dev
  region: eu-west-1
  memorySize: 1024
  logRetentionInDays: 3
  environment:
    CONNECTIONSTRINGS__DEFAULTCONNECTION: ${env:CONNECTIONSTRINGS_DEFAULTCONNECTION, ''}
    JWT__SECURITYKEY: ${env:JWT_SECURITYKEY, ''}
    SEED__EMAILADDRESS: ${env:SEED_EMAILADDRESS, ''}
    SEED__PASSWORD: ${env:SEED_PASSWORD, ''}
    EMAIL__HOST: ${env:EMAIL_HOST, ''}
    EMAIL__PORT: ${env:EMAIL_PORT, ''}
    EMAIL__USERNAME: ${env:EMAIL_USERNAME, ''}
    EMAIL__PASSWORD: ${env:EMAIL_PASSWORD, ''}
    EMAIL__NOREPLY: ${env:EMAIL_NOREPLY, ''}
    FACEBOOK__APPID: ${env:FACEBOOK_APPID, ''}
    FACEBOOK__APPSECRET: ${env:FACEBOOK_APPSECRET, ''}
    GOOGLE__CLIENTID: ${env:GOOGLE_CLIENTID, ''}

package:
  artifact: bin/release/netcoreapp2.1/deploy-package.zip

functions:
  app:
    handler: Halcyon.Api::Halcyon.Api.LambdaEntryPoint::FunctionHandlerAsync
    events:
        - http: ANY /
        - http: 'ANY {proxy+}'
